version: "3.5"

services:

  opennebula-cli:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - OPENNEBULA_VERSION=${OPENNEBULA_VERSION}
    hostname: workspace
    environment:
      - PS1=\u@\h:\w\$\040
      - ONE_XMLRPC=${ONE_XMLRPC}
      - ONE_AUTH=/root/.token
      - ONE_DISABLE_SSL_VERIFY=true
    volumes:
      - ./.token:/root/.token
      - homedir:/root
      - ./scripts:/scripts

volumes:
  homedir:
