services:
  opennebula-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - OPENNEBULA_VERSION=${OPENNEBULA_VERSION}
    hostname: workspace
    environment:
      - ONE_XMLRPC=${ONE_XMLRPC}
      - ONE_AUTH=/root/.token
      - ONE_DISABLE_SSL_VERIFY=true
    volumes:
      - ./.token:/root/.token:ro
      - ./scripts:/scripts:ro
